version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "passBirdApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rd1qacvbcwoo"
s3_prefix = "passBirdApp"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AWSAccessKeyID=\"AKIAXXKJPZR2EMB6ADGH\" AWSSecretAccessKey=\"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\" Table=\"Applications\" Region=\"ap-south-1\" AWSEnv=\"Prod\""
image_repositories = []
